#!/bin/bash
exitstatus=$?
if [ $exitstatus = 0 ]; then
    status="0"
    while [ "$status" -eq 0 ]  
    do
    choice=$(whiptail --backtitle "Программа написана на Whiptail"\
                      --title "Редактирование ауди и видео файла с помощью ffmpeg"\
                      --menu "
ffmpeg — это кроссплатформенная open-source библиотека для обработки видео- и аудиофайлов.
Клавишами верх/низ выберите справку и нажмите enter.
Для выхода выберите <Cancel>" 0 0 12 \
 "1" "Конвертировать wav в mp3" \
 "2" "Конвертировать .avi в .mpg и обратно" \
 "3" "Конвертировать видео в формат iPod/iPhone" \
 "4" "Конвертировать видео в формат PSP" \
 "5" "Конвертировать .avi в .gif (без сжатия)" \
 "6" "Конвертировать .avi в .flv" \
 "7" "Конвертировать .avi в .dv" \
 "8" "Конвертировать .avi в mpeg для DVD-плееров" \
 "9" "Редактировать файл ffmpegConvert" \
"10" "Конвертировать .mp4 в .avi" \
"11" "Конвертировать .webm в .flv" \
"12" "Конвертировать .mp3 в .ogg" \
"13" "Конвертировать .wav в .flac" \
"14" "указать больше выходных файлов" \
3>&2 2>&1 1>&3)
 option=$(echo $choice | tr '[:upper:]' '[:lower:]' | sed 's/ //g')
 case "${option}" in
         1)
whiptail --title "Конвертировать wav в mp3"\
         --msgbox "ffmpeg -i son_origine.wav -vn -ar 44100 -ac 2 -ab 192 -f mp3 son_final.mp3" 0 0
         ;;
         2)
whiptail --title "Конвертировать .avi в .mpg и обратно"\
         --msgbox "\n
 Конвертировать .avi в .mpg
 ffmpeg -i video_origine.avi video_finale.mpg\n
 Конвертировать .mpg в .avi
 ffmpeg -i video_origine.mpg video_finale.avi\n
" 0 0
      ;;
      3)
whiptail --title "Конвертировать видео в формат iPod/iPhone"\
         --msgbox "\n
ffmpeg -i source_video.avi input -acodec aac -ab 128kb -vcodec mpeg4 -b 1200kb -mbd 2 -flags +4mv+trell -aic 2 -cmp 2 -subcmp 2 -s 320x180 -title X final_video.mp3\n
" 0 0
      ;;
      4)
whiptail --title "Конвертировать видео в формат PSP"\
         --msgbox "ffmpeg -i source_video.avi -b 300 -s 320x240 -vcodec xvid -ab 32 -ar 24000 -acodec aac final_video.mp4" 0 0
      ;;
      5)
whiptail --title "Конвертировать .avi в .gif (без сжатия)"\
         --msgbox "ffmpeg -i video_origine.avi gif_anime.gif" 0 0
      ;;
      6)
whiptail --title "Конвертировать .avi в .flv"\
         --msgbox "ffmpeg -i video_origine.avi -ab 56 -ar 44100 -b 200 -r 15 -s 320x240 -f flv video_finale.flv" 0 0
      ;;
      7)
whiptail --title "Конвертировать .avi в .dv"\
         --msgbox "\n
ffmpeg -i video_origine.avi -s pal -r pal -aspect 4:3 -ar 48000 -ac 2 video_finale.dv
или
ffmpeg -i video_origine.avi -target pal-dv video_finale.dv\n
" 0 0
      ;;
      8)
whiptail --title "Конвертировать .avi в mpeg для DVD-плееров"\
         --msgbox "\n
ffmpeg -i source_video.avi -target pal-dvd -ps 2000000000 -aspect 16:9 finale_video.mpeg

Пояснения:
    Выходной формат: pal-dvd
    Максимальный размер для выходного файла: 2000000000 (2 Gb)
    Широкоэкранный формат: 16:9\n
" 0 0
      ;;
      9)
ne ffmpegConvert
     ;;
     10)
whiptail --title "Конвертировать .mp4 в .avi"\
         --msgbox "ffmpeg -i video_input.mp4 video_output.avi" 0 0
     ;;
     11)
whiptail --title "Конвертировать .webm в .flv"\
         --msgbox "ffmpeg -i video_input.webm video_output.flv" 0 0
     ;;
     12)
whiptail --title "Конвертировать .mp3 в .ogg"\
         --msgbox "ffmpeg -i audio_input.mp3 audio_output.ogg" 0 0
     ;;
     13)
whiptail --title "Конвертировать .wav в .flac"\
         --msgbox "ffmpeg -i audio_input.wav audio_output.flac" 0 0
     ;;
     14)
whiptail --title "указать больше выходных файлов:"\
         --msgbox "ffmpeg -i audio_input.wav audio_output_1.mp3 audio_output_2.ogg" 0 0
     ;;
      *) status=1
        exit
            ;;
        esac
    done
else
    exit
fi
